## DONE!!!
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.
#https://projecteuler.net/problem=2
#
#4613732 ANS
#3 ms

start = Time.now
def fibonacci
  prev = 1
  cur = 2
  new_n = 0
  sum_even = 0
  while new_n < 4000000
    sum_even += cur  if even?(cur) 
    new_n = prev + cur
    prev = cur
    cur = new_n
  end
  sum_even
end

def even?(number)
  number % 2 == 0 ? true : false
end

puts fibonacci
puts Time.now - start
